name: Test Variables
on:
  push:
    branches: 
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    #strategy:
     #   matrix:
     #     environment: [ dev, test ]
          
    #environment:  ${{ matrix.environment }}  
    environment:  dev  
    steps:

      # Checks-out the repository under $GITHUB-WORKSPACE 
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Obtiene directorios
        run: ls
      # Runs a set of commands using the runners Shell (Running a Python Script)     
      #- name: Echo the message
      #  uses: gchacon054/pokedex-for-ci/.github/actions/bootstrap/action.yaml@main
      #  with:
      #    mascot: "Test Mascot" 
        #run: |
        #  echo "Hola midu!  ${{ vars.mascot }}" 
