name: Test Variables

on:
  push:
    branches: 
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    strategy:
        matrix:
          environment: [ dev, test ]
          
    environment:  ${{ matrix.environment }}  
    steps:

      # Checks-out the repository under $GITHUB-WORKSPACE 
      - name: Checkout repo
        uses: actions/checkout@v3
        
      # Runs a set of commands using the runners Shell (Running a Python Script)
      - name: Run playbook
        run: ls -l
             echo 'Hi ${{ vars.mascot }}'  
